[project]
name = "hydra-auth"
version = "0.1.0"
requires-python = ">=3.14,<4"
dependencies = [
    "hydra",
]

[tool.uv.workspace]
members = [
    "backend",
]

[tool.uv.sources]
hydra = { workspace = true }

[dependency-groups]
dev = [
    "black>=26.1.0",
    "mypy>=1.19.1",
]

[tool.mypy]
strict = true
pretty = true
show_error_codes = true

plugins = [
    "pydantic.mypy",
]

[tool.pydantic-mypy]
init_typed = true
init_forbid_extra = true
warn_untyped_fields = true
warn_required_dynamic_aliases = true
